const express = require('express');
const axios = require('axios');
const cors = require('cors');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5001;

app.use(cors());
app.use(express.json());

app.post('/api/words', async (req, res) => {
  try {
    const response = await axios.post('https://api.anthropic.com/v1/messages', {
      model: 'claude-3-sonnet-20240229',
      max_tokens: 50,
      messages: [{
        role: 'user',
        content: 'Generate two familiar, concrete English words that are not commonly paired together. The pairing should be unusual and thought-provoking, but not nonsensical or fantastical. Return ONLY the two words, separated by a single space, with no other text.'
      }]
    }, {
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'anthropic-beta': 'messages-2023-12-15'
      }
    });
    console.log('LLM response:', response.data);
    const newWords = response.data.content[0].text.trim().toLowerCase().split(' ');
    res.json({ words: newWords });
  } catch (error) {
    console.error('Backend error:', error.message);
    res.status(500).json({ error: 'Failed to fetch words.' });
  }
});

app.post('/api/analyze', async (req, res) => {
  const { responses } = req.body;
  if (!responses || !Array.isArray(responses) || responses.length === 0) {
    return res.status(400).json({ error: 'No responses provided for analysis.' });
  }
  try {
    const prompt = `Here are the last 5 writing responses from a user participating in a creative writing prompt app. Each response was written using a different random word pair (the 'seed phrase'), which was generated by AI and may be odd or unusual. IMPORTANT: Do NOT analyze or judge the quality of the seed phrases themselves. Instead, focus only on how the user incorporated each seed phrase into their writing. Please analyze the user's writing as a whole: offer insights, suggestions for improvement, or observations about their style, creativity, or themes. Be supportive and constructive.\n\nUser responses:\n${responses.map((r, i) => `${i+1}. ${r}`).join('\n')}\n\nAnalysis:`;
    const response = await axios.post('https://api.anthropic.com/v1/messages', {
      model: 'claude-3-sonnet-20240229',
      max_tokens: 200,
      messages: [{
        role: 'user',
        content: prompt
      }]
    }, {
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'anthropic-beta': 'messages-2023-12-15'
      }
    });
    const analysis = response.data.content[0].text.trim();
    res.json({ analysis });
  } catch (error) {
    console.error('Analysis backend error:', error.message);
    res.status(500).json({ error: 'Failed to analyze writing.' });
  }
});

app.listen(PORT, () => {
  console.log(`Backend server running on port ${PORT}`);
});
