const express = require('express');
const axios = require('axios');
const cors = require('cors');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5001;

app.use(cors());
app.use(express.json());

app.post('/api/words', async (req, res) => {
  try {
    const response = await axios.post('https://api.anthropic.com/v1/messages', {
      model: 'claude-3-sonnet-20240229',
      max_tokens: 50,
      messages: [{
        role: 'user',
        content: `You are a creative assistant designed to inspire writers by generating uncommon and intriguing word pairings. Your goal is to provide a diverse set of combinations that can spark new ideas, break creative blocks, and encourage users to think outside the box.
Please generate unique word pairings one at-a-time. Aim to provide a mix of the following two styles, or focus on one if specified by a later user instruction:

Style 1: Evocative & Thought-Provoking Combinations
- Objective: Create pairings that are more literary, metaphorical, or sensory. These should hint at deeper meanings, evoke specific moods, or blend concepts in an original and thought-provoking way.
- Characteristics to aim for:
  - Juxtaposition of abstract concepts with concrete imagery (e.g., "Velvet Gravity," "Fossilized Dreams").
  - Pairings that suggest a story, emotion, or unique sensory experience (e.g., "Rust-Kissed Memory," "Brittle Laughter").
  - Combinations that assign unexpected qualities or agency to objects or concepts (e.g., "Nomadic Starlight").
  - Use evocative adjectives and nouns, and don't shy away from slightly more sophisticated vocabulary, but maintain clarity.
  - Think: poetic, atmospheric, subtly surprising, insightful.
Style 2: Quirky & Mundane Mashups
- Objective: Create pairings from everyday words that are amusing, absurd, or delightfully illogical. These should be instantly accessible and spark fun by their sheer unexpectedness.
- Characteristics to aim for:
  - Combine common, everyday nouns and concepts in ways that defy normal semantic relationships (e.g., "lemonade scissors," "hair gravy," "Toast Cuddles").
  - Focus on creating a mental double-take or a humorous, surreal image (e.g., "Sofa Berries," "Clockwork Soup").
  - Keep the language simple and direct. The novelty comes from the oddness of the combination itself, not complex vocabulary.
  - Think: playful, absurd, whimsically strange, simple but effective.
General Guidelines for All Pairings:
- Brevity: Most pairings should be two words, occasionally three if it enhances the effect.
- Inspiration, not Prescription: These pairings are meant to be starting points for the writer's own creativity.
- Variety: If providing a mix, ensure a good balance between the two styles.
- Tone: Maintain an underlying tone of creative encouragement.

Please provide new word pairings when prompted. Return ONLY the word pairing, and nothing else.`
      }]
    }, {
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'anthropic-beta': 'messages-2023-12-15'
      }
    });
    console.log('LLM response:', response.data);
    const newWords = response.data.content[0].text.trim().toLowerCase().split(' ');
    res.json({ words: newWords });
  } catch (error) {
    console.error('Backend error:', error.message);
    res.status(500).json({ error: 'Failed to fetch words.' });
  }
});

app.post('/api/analyze', async (req, res) => {
  const { responses } = req.body;
  if (!responses || !Array.isArray(responses) || responses.length === 0) {
    return res.status(400).json({ error: 'No responses provided for analysis.' });
  }
  try {
    const prompt = `Here are the last 5 writing responses from a user participating in a creative writing prompt app. Each response was written using a different random word pair (the 'seed phrase'), which was generated by AI and may be odd or unusual. IMPORTANT: Do NOT analyze or judge the quality of the seed phrases themselves. Instead, focus only on how the user incorporated each seed phrase into their writing. Please analyze the user's writing as a whole: offer insights, suggestions for improvement, or observations about their style, creativity, or themes. Be supportive and constructive.\n\nUser responses:\n${responses.map((r, i) => `${i+1}. ${r}`).join('\n')}\n\nAnalysis:`;
    const response = await axios.post('https://api.anthropic.com/v1/messages', {
      model: 'claude-3-sonnet-20240229',
      max_tokens: 200,
      messages: [{
        role: 'user',
        content: prompt
      }]
    }, {
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': process.env.ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'anthropic-beta': 'messages-2023-12-15'
      }
    });
    const analysis = response.data.content[0].text.trim();
    res.json({ analysis });
  } catch (error) {
    console.error('Analysis backend error:', error.message);
    res.status(500).json({ error: 'Failed to analyze writing.' });
  }
});

app.listen(PORT, () => {
  console.log(`Backend server running on port ${PORT}`);
});
